name: Build and deploy to Azure Web App (OIDC)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # OIDCでAzureにログイン（Deploy Centerが作成した既存のSecrets名を使用）
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DDF2445764E8464A8A02F7BE062F45A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4BA2F9B4ECAA402A82BE2676064139E1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9D3E0A455F504E74A34E1387D620A199 }}

      # Pythonバックエンドの依存をインストール（正しいパス）
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install backend deps
        run: python -m pip install -r app/backend/requirements.txt

      # フロントエンドをビルド
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build frontend
        working-directory: app/frontend
        run: |
          npm ci
          npm run build

      # App Serviceへデプロイ（Publish Profile不要／OIDCコンテキスト）
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-rag-attach
          slot-name: Production
          package: .
